# Generated by Django 2.0 on 2018-05-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_card_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_card',
            name='tags',
            field=models.ManyToManyField(to='products.Tag'),
        ),
    ]
