# Generated by Django 2.0 on 2018-05-24 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_contacto_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
